### ISSUE TITLE
Add video capture support to replay tool

### ISSUE THREAD

**Issue by myaaaaaaaaa** [LunarG/gfxreconstruct#1020]
The recent Vulkan Video extensions opens up the opportunity for having zero-copy(?), hardware-accelerated video capture support integrated directly into the replay tool. Even a barebones implementation of recording to a raw .264 bitstream would provide a much smoother experience than the current method of screenshotting a .bmp sequence.

Of course, it may be a good idea to [wait until the extensions are finalized first](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode#:~:text=The%20following%20encode%2Drelated%20extensions%20remain%20provisional%20and%20are%20expected%20to%20be%20finalized%20in%202023).

**Comment by bradgrantham-lunarg** [comment]
Hi!  Thanks for your suggestion.  GFXR is currently most frequently used in regression testing and bug reporting.  For that purpose actual frame grabs of the presented swapchain image are great for pixel comparisons and inspection.  It's not clear to us how a lossy video output could be used in correlation with that.  Can you provide more detail about how you'd use a lossy video output?

**Comment by myaaaaaaaaa** [comment]
In the context of bug reporting, there would be some mild benefit in making it easier to share and work with longer traces by making it possible to scrub through them in an external video player - presumably not every regression/bug requires pixel level comparisons.

Beyond that, I'm more interested in seeing an increase in the utility of `.gfxr` as a lossless video format (which it essentially is). There's a lot of demand for recording video game footage these days - see [NVIDIA's ShadowPlay](https://www.nvidia.com/en-us/geforce/geforce-experience/shadowplay/) or [Godot's recently added Movie Maker mode](/godotengine/godot/pull/62122) for examples - and doing this from the API trace level has certain advantages (and disadvantages, of course) over standard desktop capturing tools like [Open Broadcaster Software](https://obsproject.com/). Integrating Vulkan Video encoding directly into GFXReconstruct would greatly improve its usability for this purpose.

Having more people creating and using `.gfxr` files this way - even if only by game developers for making prerendered game footage - would help driver developers indirectly, as it would inevitably result in more `.gfxr` files being made available for driver testing.

Of course, feel free to close this if implementing Vulkan Video encoding would be too cumbersome - there's always the option of `--screenshot-all`ing to a .bmp sequence and converting it afterwards using ffmpeg.

**Comment by andrew-lunarg** [comment]
That's an interesting idea, thank you.

So to summarise, the main usage would be to record gameplay footage without sound in a two-step process, firstly capturing an API trace while the game is played, and secondly by having replay use video extensions to record the video with very low overhead.
The advantage here is the assumption that API capture has lower overhead than video capture by an external application while the game is being played, so that the game's framerate stays steady.

Since the feature being added to replay would be a quality of life boost rather than essential to the workflow, I think it would be good to get some experience out there from people doing this with the `--screenshot-all` option and confirming that it basically does what people need (the result is superior to screen capturing the game) and that there's sufficient use of it to warrant some development work to support the video encoding step at replay. It might always be too low a priority for us to do internally though when set against core features on the roadmap but I'd be interested to look at a PR.

**Comment by myaaaaaaaaa** [comment]
Okay. Thank you for your consideration!
