### ISSUE TITLE
[gfxrecon-convert] About Index continuity of jsonl

### ISSUE THREAD

**Issue by chenyangchenyang** [LunarG/gfxreconstruct#1031]
Hi,

I get a jsonl file by  gfxrecon-convert option (mobile & vulkan)

![image](https://user-images.githubusercontent.com/28689129/224687844-2f6c0193-f8fa-4a4a-8be4-7c555c17c0a2.png)

I found that **CMD Index Not Continuity** 

What is cmd  about  indice of  range (6345005, 6345044)

**Comment by panos-lunarg** [comment]
When GFXR creates a capture file it does not store only the Vulkan commands. There are other internal commands than need to be stored in order to be able to replay the file. Few examples:
- When the user updates the contents of uniform buffer, or device memory mapped to user space in general (remember the page guard mechanism we talked about in the UE project issue)
- When AndroidHardwareBuffers are imported in the original application. GFXR needs to store information about that buffer in order to (attempt to) recreate it when replaying
- State initialization when doing trimmed captures

Convert will output only the Vulkan commands, skipping the internals. This explains the non consecutive order of the indices

**Comment by andrew-lunarg** [comment]
Panos explained it clearly: the index is intended to be the index of the block in the binary file. I'd add that:
1. We have support for more block types than functions on branches that haven't merged yet and will aim to add them all to Convert.
1. The D3D/DX12 experimental Convert JSON output uses a different numbering currently but will be changed to have block indexes like this too.

**Comment by chenyangchenyang** [comment]
Thanks for your replay
