### ISSUE TITLE
VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT handling

### ISSUE THREAD

**Issue by zmike** [LunarG/gfxreconstruct#1080]
If a trace is captured from an app that uses VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT, this can cause the trace to be unreplayable on other versions of the driver. For example:

**app capture**
* pipeline cache exists for driver version A
* app uses pipeline cache and sets VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT to create pipeline library
* app gets pipeline cache hit
* pipeline libraries from above are used to create full pipeline
* execution continues
* capture end

* driver version changes to B
  * pipeline cache is invalidated

**trace replay**
* trace uses pipeline cache and sets VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT to create pipeline library
* trace does not get pipeline cache hit
* null pipeline libraries are passed to create full pipeline
  * illegal behavior
  * crash

I'm not sure what the "correct" solution is here (maybe even just a warning in stdout?) but I think it's worth raising as an issue.

**Comment by danginsburg** [comment]
This impacts capturing any Source 2 games so for example can be reproduced with Dota 2.  When I use gfxrecon I have to run with a command-line option to disable VK_EXT_pipeline_creation_cache_control to workaround this issue (`vulkan_disable_ext_pipeline_creation_cache_control`).

**Comment by locke-lunarg** [comment]
This error is to make sense. Because the pipeline cache was invalidated, so it needed to compile. But it had `VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT` flag, so `vkCreateGraphicsPipelines` returned `VK_PIPELINE_COMPILE_REQUIRED` and pipeline was `VK_NULL_HANDLE`. And then, because pipeline was `VK_NULL_HANDLE`, it crashed in the following command that was related to pipeline.

We might have a couple solutions.
1. Require user to get a new capture to have a new pipeline cache.
2. Add a option to disable VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT flag for replay.
3. I think you do something in your program, when `VK_PIPELINE_COMPILE_REQUIRED` happens. We could do the same thing if you tell us what you do.

I think No. 2 could be a better idea. What do you think? @zmike @bradgrantham-lunarg 



vkspec:
VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT specifies that pipeline creation will fail if a compile is required for creation of a valid VkPipeline object; VK_PIPELINE_COMPILE_REQUIRED will be returned by pipeline creation, and the VkPipeline will be set to VK_NULL_HANDLE.

**Comment by danginsburg** [comment]
In my personal view, I think gfxrecon should never return VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT, the traces are likely going to not be replayable since the most likely reason an app is asking is to avoid compiling a pipeline.  Since you don't have access to the cache data (it might have come from an internal driver cache rather than a loaded VkPipelineCache) this just seems like it's not going to work in most cases.

**Comment by bradgrantham-lunarg** [comment]
I think we could have an option (default on?) to always return COMPILE_REQUIRED if the application passed `VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT` to `vkCreate*Pipelines`.  Would that work?

**Comment by bradgrantham-lunarg** [comment]
My response was before you edited your comment - I think that sounds like a plan.

**Comment by locke-lunarg** [comment]
@zmike  @danginsburg  could you help to view this PR? Thank you very much. 
https://github.com/LunarG/gfxreconstruct/pull/1160

**Comment by zmike** [comment]
@locke-lunarg I'm not familiar with the gfxreconstruct codebase, but at a conceptual level the change seems like it should resolve this issue. Thanks!

**Comment by danginsburg** [comment]
I am in the same boat, looks OK to me but I'm not familiar with the code base.

**Comment by bradgrantham-lunarg** [comment]
#1160 was merged.  @danginsburg and @zmike do you think you will have a chance to try out this change in `dev`?
