### ISSUE TITLE
Why the generated header and cpp are not generated in build time?

### ISSUE THREAD

**Issue by jyangsh** [LunarG/gfxreconstruct#268]
It looks the generated cpp and header files are checked in the repo. Why they are not generated in the build time?

**Comment by dustin-lunarg** [comment]
The generated files are checked into the repo and not generated at build time because they only need to be regenerated when either the Vulkan header is updated or the generator scripts are modified.  Because the files don't need to be generated for each build, the code generation was moved to an offline process to remove a build dependency on Python and reduce overall build time.  Checking the files into the repository also makes it easy to review changes to the generated code.

Open issue #201 describes some CMake improvements to be made in the future, which includes an option to enable the code generation at build time.  This option would be intended for developers that are actively editing the code generation scripts and would benefit from a code generation build step.  This is a low priority task, and I do not currently have an estimate for when it would be addressed.

**Comment by jyangsh** [comment]
Thanks for explain. Just want to find the way how to use these script to generate the cpp/header files.
Looks just run the "generate_vulkan.py" is okey.

**Comment by dustin-lunarg** [comment]
Running 'generate_vulkan.py' is the easiest way to generate all of the files.
