### ISSUE TITLE
Implement Portability Mode: Swapchain Adjustment

### ISSUE THREAD

**Issue by dustin-lunarg** [LunarG/gfxreconstruct#277]
For replay on systems with swapchains supporting different presentation modes and different min/max image requirements than the capture system, swapchain interaction will need to be adjusted.  One potential solution would be to substitute VkImage objects with color attachment usage for swapchain images at image acquire, and then blit the substituted image to the appropriate swapchain image at queue present.

**Comment by per-mathisen-arm** [comment]
Is the intention to do this always or only when required - and if so, would it be explicitly enabled? I ask because it will have a performance impact, and it would be nice to know and able to control when it triggers.

Also, is the intention to use such virtual swapchain images to handle the case of swapchain image reordering? As order you get images from vkAcquireNextImage may differ between trace and replay (even if you have the same number of images), and some content may encode swapchain image references into persistent commandbuffers.

**Comment by dustin-lunarg** [comment]
This would be implemented as an optional replay mode that would be explicitly enabled.  It would provide a solution to the swapchain image reordering issue, but to avoid altering the workload on replay we may also look for an additional solution to the reordering problem that extends this proposed change to vktrace to handle the persistent command buffer case: Lunarg/VulkanTools#368

**Comment by lunarpapillo** [comment]
We have a variety of traces intended for testing that have been disabled due to unreliability, that we suspect are due to swapchain image ordering.   I'd like to start archiving these here, so we can know which traces we should reinvestigate for testing use after there's a solution for the virtual swapchain.

This is from the `f12017` trace for Linux AMD: http://tcubuser/cgi-bin/server.py?request=results-compare&reference=12406c844032b423c5b2781f64138b954b82169959ebae98b354033a120f62a6&generated=a393284accec367613eb62a794941a9cbcc3ba5fe6e98b5abbc7919cf35e7968

**Comment by locke-lunarg** [comment]
https://github.com/LunarG/gfxreconstruct/pull/701
It's about virtual swapchain. Merged. Closed.
