### ISSUE TITLE
AMD RX580 Dota2 trace doesn't trim correctly to frame 30

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#287]
The trace I'm using is in `\\nas\smb_traces\vulkan\GFXR\papillo-amd\dota2\dota2_20190213T193643.gfxr`.  This trace was created on Ubuntu 18.04 with an AMD RX 580 graphics card.

To reproduce, capture the image at (0-based) frame 30, then trim the trace to just (1-based) frame 31.  Replay the trimmed trace and capture (0-based) frame 0.  The two images do not match.

With an appropriate `PATH` (that contains `gfxrecon-replay`) and `VK_LAYER_PATH` (that contains the `screenshot` and `gfxreconstruct` layers):

```bash
# Local copy of the file
cp /media/nas/smb_traces/vulkan/GFXR/papillo-amd/dota2/dota2_20190213T193643.gfxr dota2.gfxr

# Create image for frame 30 (screenshot frames are 0-based)
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_screenshot
export VK_SCREENSHOT_FRAMES=30
gfxrecon-replay dota2.gfxr

# Trim to the same frame (GFXR frames are 1-based)
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
export GFXRECON_CAPTURE_FRAMES=31
gfxrecon-replay dota2.gfxr

# Replay trimmed trace and capture frame 0
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_screenshot
export VK_SCREENSHOT_FRAMES=0
gfxrecon-replay gfxrecon_capture_frame_31_XXXX.gfxr

# Examine the two frames
eog 0.ppm 30.ppm
```

**Comment by lunarpapillo** [comment]
On my system, this is the reference image `30.ppm` (converted to `png` because GitHub doesn't like `ppm`, and scaled to a reasonable size):
![30](https://user-images.githubusercontent.com/45772930/64989954-00166700-d88c-11e9-8ba0-62b4b7570eea.png)

And this is the generated image `0.ppm`:
![0](https://user-images.githubusercontent.com/45772930/64989984-0c022900-d88c-11e9-8c26-abb2d5e2f69e.png)

**Comment by lunarpapillo** [comment]
For completeness, Dota2 fails on keyframes 30, 1286, 1679, 2143, 2224, 2357, and 3574, all with similar garbage screens.  It passes on keyframe 0. On keyframes 1794 and 3687, the screen is intelligible, but seems to not be the same frame as the reference frame.

**Comment by dustin-lunarg** [comment]
There are currently some cases where the state setup for the trimmed frame will acquire and present swapchain images before rendering the frame.  The screenshot layer cannot differentiate between the calls to vkQueuePresentKHR performed by the state setup and the vkQueuePresentKHR performed for the trimmed frame.  What you are seeing is a screenshot of one of the images that was acquired, transitioned to the PRESENT_SRC_KHR layout, and presented for the initial state setup.  

The replay tool will eventually have support for generating screenshots, where it would ignore the vkQueuePresentKHR calls performed for the initial setup.  Until the screenshot feature is added to the replay tool, the frame numbers provided to the screenshot layer will need to be adjusted to account for the additional vkQueuePresentKHR calls performed by the state setup.

The number of calls to vkQueuePresentKHR can vary based on the number of available swapchain images and the index of the image that the trimmed frame expects to acquire (e.g. If the trimmed frame expects to acquire the third swapchain image, the initial setup will acquire and present the first two images in an attempt to set a state where the image acquired when replaying the trimmed frame is the third image).  

Because the number of initial calls to vkQueuePresentKHR can vary, you will either need to manually determine the appropriate frame number for each trimmed capture file, or do something like generate a screenshot for every frame and then pick the last generated screenshot as the screenshot for the rendered frame.

There are some implementations that allow all swapchain images to be acquired at the same time.  The replay tool uses the following logic from the vkAcquireNextImageKHR valid usage to attempt to determine that all images can be acquired at the same time:

>If the number of currently acquired images is greater than the difference between the number of images in swapchain and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to create swapchain, timeout must not be UINT64_MAX

If the replay tool can determine that all images can be acquired at the same time, it will acquire all images at state setup and keep them acquired until first use to avoid making additional calls to vkQueuePresentKHR.

**Comment by lunarpapillo** [comment]
Verified.  Closing.
