### ISSUE TITLE
VK_LAYER_PATH is ignored

### ISSUE THREAD

**Issue by pemgithub** [LunarG/gfxreconstruct#474]
I set VK_LAYER_PATH , but when I attach visual studio debugger, it seems to be using "C:\Programs\VulkanSDK\1.2.148.1\Bin\VkLayer_gfxreconstruct.dll".  How do I tell it to use "gfxreconstruct\build\windows\x64\output\bin\VkLayer_gfxreconstruct.dll".

**Comment by dustin-lunarg** [comment]
Using VK_LAYER_PATH with an absolute path like:
```cmd
C:\> set VK_LAYER_PATH=C:\gfxreconstruct\build\windows\x64\output\bin
C:\> set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
C:\> myapp.exe
```
Should result in `myapp.exe` loading the gfxreconstruct layer from `C:\gfxreconstruct\build\windows\x64\output\bin`.

How are you setting the VK_LAYER_PATH environment variable?

As an alternative to setting VK_LAYER_PATH, you could also try using vkconfig to enable the capture layer.

**Comment by pemgithub** [comment]
Yes - I am running this:
`set VK_LAYER_PATH=D:\PemCode\gfxreconstruct\build\layer\Debug
set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
myapp.exe
`
However, for some reason it still uses "C:\Programs\VulkanSDK\1.2.148.1\Bin\VkLayer_gfxreconstruct.dll".

I will try vkconfig

**Comment by pemgithub** [comment]
vkconfig seems to work 👍
![image](https://user-images.githubusercontent.com/13956322/101971063-479cb780-3be3-11eb-8dcb-e308f3633181.png)

**Comment by dustin-lunarg** [comment]
Since it looks like you were able to get something to work with vkconfig, I will go ahead and close this issue.  Because VK_LAYER_PATH is an environment variable used by the Vulkan Loader to determine where to look for layers, and is not something specific to this project, there isn't really much we can do outside of specifying what it should be set to.
