### ISSUE TITLE
Error with latest Mesa-git and Cyberpunk2077

### ISSUE THREAD

**Issue by ErikReider** [LunarG/gfxreconstruct#488]
When trying to capture calls, I get this error:
```
INFO: Inserted device layer VK_LAYER_LUNARG_gfxreconstruct (/home/erikreider/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so)
[gfxrecon] ERROR - VkPhysicalDeviceBufferDeviceAddressFeatures::bufferDeviceAddressCaptureReplay is needed to capture device addresses, but it is not supported by the capture device.
[gfxrecon] WARNING - A pNext value with unrecognized VkStructureType = 1000351002 was omitted from the capture file, which may cause replay to fail.
[gfxrecon] WARNING - A pNext value with unrecognized VkStructureType = 1000351002 was omitted from the capture file, which may cause replay to fail.
[gfxrecon] WARNING - Attempting to initialize descriptor state for unrecognized descriptor type
```
With a Wine error in the end
```
wine: Unhandled page fault on read access to 0000000000008664 at address 000000007BC62DD0 (thread 0174), starting debugger...
```
Works with the latest Mesa-stable (20.3.1) but not with Mesa 21.0.0-devel (git-3898f747ce)
These are my exports:
```
export GFXRECON_CAPTURE_FILE_FLUSH=1
export VK_LAYER_PATH=~/gfxreconstruct/build/layer:$VK_LAYER_PATH
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
export VK_LOADER_DEBUG=all
export GFXRECON_CAPTURE_FILE=~/gfxrecon_capture.gfxr
export GFXRECON_CAPTURE_TRIGGER=F3
```

**Comment by ErikReider** [comment]
Apparently, the export `GFXRECON_CAPTURE_TRIGGER=F3` caused the issue. Could be helpful for anyone else experiencing this issue

**Comment by dustin-lunarg** [comment]
The warnings suggest that the VK_VALVE_mutable_descriptor_type extension is enabled, which is not currently supported.  That extension was introduced with the 1.2.164 header, and we are only up to date with the 1.2.162 header.

If there was a crash during capture with `GFXRECON_CAPTURE_TRIGGER=F3`, which went away when that option is removed, you may still see issues during replay due to lack of support for VK_VALVE_mutable_descriptor_type.

**Comment by ErikReider** [comment]
@davidd-lunarg thanks! I didn't even get into the game 😂
