### ISSUE TITLE
gfxrecon-info produces no helpful information for captures that don't present a frame

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#585]
This was observed on a Linux Mesa AMD machine using a trace of `vulkaninfo`, which does Vulkan calls but does not produce any Vulkan output.  I imagine the problem could also occur with a compute-only trace.
```
$ gfxrecon-info --version
gfxrecon-info version info:
  GFXReconstruct Version 0.9.9-dev (dev:7f6b3c6)
  Vulkan Header Version 1.2.189
$ gfxrecon-info /media/nas/smb_traces/vulkan/GFXR//windows-nvidia/vulkaninfo/vulkaninfo_20201110T115442.gfxr
[gfxrecon] WARNING - Pointer decoder's external memory capacity (8) is smaller than the decoded array size (16); data will be truncated
File did not contain any frames
```
I expected all the information about the file that's normally available to output traces, e.g.:
```
$ gfxrecon-info /media/nas/smb_traces/vulkan/GFXR//windows-nvidia/baldursgate3/baldursgate3_20201023T150706.gfxr 
[gfxrecon] WARNING - Incomplete block at end of file
File info:
	Compression format: LZ4
	Total frames: 8855

Application info:
	Application name: Baldur's Gate 3
	Application version: 1096026085
	Engine name: The Divinity Engine
	Engine version: 1096026085
	Target API version: 4198400 (1.1.0)

Physical device info:
	Device name: GeForce RTX 2080 SUPER
	Device ID: 0x1e81
	Vendor ID: 0x10de
	Driver version: 1913765888 (0x7211c000)
	API version: 4202638 (1.2.142)

Device memory allocation info:
	Total allocations: 80
	Min allocation size: 256
	Max allocation size: 877050880

Pipeline info:
	Total graphics pipelines: 5917
	Total compute pipelines: 27
```
## Other nits
In addition to `Total frames`, the tool should also output `Total commands` (which is more interesting for traces that have no identifiable frames)

**Comment by bradgrantham-lunarg** [comment]
Agreed, replay should print out information for vulkaninfo and compute-only captures just like visual captures.  However, is it possible this particular capture showing the same issue as https://github.com/LunarG/gfxreconstruct/issues/584 ?  I ask because it outputs 
`[gfxrecon] WARNING - Pointer decoder's external memory capacity (8) is smaller than the decoded array size (16); data will be truncated`

**Comment by bradgrantham-lunarg** [comment]
@patrick-lunarg verified vulkaninfo does not display information like windowed programs, so we should investigate.

**Comment by bradgrantham-lunarg** [comment]
`info` only produces output [if there are frames](https://github.com/LunarG/gfxreconstruct/blob/7b71221f67f163440cfc3c44d834ac0ac2149916/tools/info/main.cpp#L539).

I think we could print the compression format if we were able to read the file header.

We probably could add to `StatsConsumer` a finer-grained status to let us know if sets of the fields are set.  After `CreateInstance` we should be able to print the app and engine name and version and the API version requested.

Since device info is an array, we should be able to print every entry, which may be zero entries.

We'd still have to print `File did not contain any frames` if it did not.
