### ISSUE TITLE
Release source artefacts are not buildable

### ISSUE THREAD

**Issue by charlie-ht** [LunarG/gfxreconstruct#600]
Hi,

I expected the following to work,

```
GFXR_SRC_DIR=/tmp/gfxr-src
GFXR_RELEASE_VERSION=v0.9.9
wget -S --progress=dot:giga -O- \
     https://github.com/LunarG/gfxreconstruct/archive/refs/tags/"${GFXR_RELEASE_VERSION}".tar.gz | \
    tar -xz --strip-components=1 -C "$GFXR_SRC_DIR"
pushd "$GFXR_SRC_DIR"
cmake -S . -B _build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_WERROR=OF
cmake --build _build --parallel
cmake --build _build install
popd
rm -rf "$GFXR_SRC_DIR"
```

But I get an error,

```
-- Vulkan Header = VULKAN_HEADER-NOTFOUND
CMake Error at cmake/FindVulkanVersion.cmake:30 (file):
  file STRINGS file "/tmp/test/VULKAN_HEADER-NOTFOUND" cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:102 (include)


CMake Error at cmake/FindVulkanVersion.cmake:59 (message):
  Failed to find major version in VULKAN_HEADER-NOTFOUND
Call Stack (most recent call first):
  CMakeLists.txt:102 (include)
```

From the same tag `v0.9.9` in git, the build works. I then realised the source artefact does not contain the submodule source code. If it did, the build would work, finding the vulkan header in the `external/Vulkan-Headers` subtree, just like the git checkout does.

**Comment by bradgrantham-lunarg** [comment]
We build with a specific version of the headers/xml because we have to update the source code when new functions / structures / enumerants are added to Vulkan.  So we include the specific version as a submodule.  We document several ways to build from source.  We currently don't plan to include a way to download a tar.gz from github and build from there.
