### ISSUE TITLE
Flags should be printed as expanded flag values

### ISSUE THREAD

**Issue by ghost** [LunarG/gfxreconstruct#620]
Currently flags are output as their decimal values.
Flags should output string values.
If flags contain multiple values OR'd together, they should expand out as follows:
"FLAG_STRING_VALUE_0 | FLAG_STRING_VALUE_1"

**Comment by andrew-lunarg** [comment]
Note that all the functions like the following in `framework/generated/generated_vulkan_enum_to_string.cpp` for outputting the desired masks are never called. Their signatures can be changed and the repo still builds fine, showing they are never called from anywhere in the codebase.

```cpp
template <> std::string ToString<VkAccessFlagBits>(VkFlags vkFlags, ToStringFlags, uint32_t, uint32_t)
{
    return BitmaskToString<VkAccessFlagBits>(vkFlags);
}
```

I think the delay in plumbing them comes from them not fitting into the scheme of using types to dispatch to template `ToString` function specialisations. In other cases dealing with distinct types like struct and enums that lets the Python code generation be simple and leverages the function resolution rules of C++ to make sure the right code is called. In this case, these flag set are coming through as typedefs of `VkFlags` or `VkFlags64`, which are indistinguishable from any other `uint32_t` or `uint64_t` at the C++ level in the generated code.

The fix requires the Python generator code to use its knowledge of the flag set being handled at each calling site to explicitly specify which template specialisation to hand them over to, rather than dumping them into the generic `ToString()` as is done now. For example,

```cpp
    // Inside the ToString() for VkBufferMemoryBarrier:
    // Instead of:
    FieldToString(strStrm, false, "srcAccessMask", toStringFlags, tabCount, tabSize, 
        ToString(obj.srcAccessMask, toStringFlags, tabCount, tabSize)); // < bad!
    // Do this:
    FieldToString(strStrm, false, "srcAccessMask", toStringFlags, tabCount, tabSize,
        ToString<VkAccessFlagBits>(obj.srcAccessMask, toStringFlags, tabCount, tabSize)); // < good!
```
In fact I don't believe `ToString<VkAccessFlagBits>` needs to be a template specialisation at all and a plain function like in the example above `VkAccessFlagBitsToString(VkFlags flags)` would be clearer and simpler, and we should take this opportunity to make a change to their signatures while we are touching this code, but above is how we would plumb in the functions exactly as they are generated today.

I've noted this in another issue or PR previously but the only reason all these hundreds of ToString() functions are template specialisations at all is so that the few cases for primitive types like ints and floats can share a single template. Now we ignore most of the parameters to `ToString()` functions (`toStringFlags, tabCount, tabSize`), because we are not formatting output, and they are going to be deleted at some point, that template base case could just use the standard `std::to_string()` that it wraps anyway, or they could be handled by a bunch of non-template one liners that still wrap `to_string()` for those of us who like to be able to put a breakpoint on float output and only float output (for example).

**Comment by andrew-lunarg** [comment]
64 bit flags must also be supported. Their functions will say the following by the time this issue is being fixed:
```c++
std::string VkPipelineStageFlags2ToString(VkFlags64 vkFlags)
{
    // return BitmaskToString<VkPipelineStageFlagBits2>(vkFlags);
    return "Unimplemented";
}
```
We need to either make BitmaskToString always take a 64 bit argument (for simplicity) or provide a second, otherwise identical,  version of it that does.

**Comment by andrew-lunarg** [comment]
Note, the work has to touch all the calling sites that can see a set of flags and so needs to know based on a-priori programmer knowledge or type info available in the Python generator base class which function to call. These include:


* `framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py` (flags in function arguments)
* `framework/generated/vulkan_generators/vulkan_struct_to_string_body_generator.py`
* `framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py`
* `framework/decode/vulkan_ascii_consumer_base.cpp`
* `framework/util/custom_vulkan_to_string.cpp`
* `framework/decode/custom_vulkan_struct_decoders_to_string.cpp`

**Comment by andrew-lunarg** [comment]
We got this with the external contribution of the tool previously known as Export. Try the option `--expand-flags` to see this in action.
